//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtdelLogistiki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиE", new string[] {
            "Наименование as \'Наименование\'",
            "IDДолжности as \'I d должности\'",
            "Персонал as \'Персонал\'",
            "Персонал.Контакты as \'Контакты\'"}, Hidden=new string[] {
            "Персонал.Контакты"})]
    [MasterViewDefineAttribute("ДолжностиE", "Персонал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контакты")]
    [View("ДолжностиL", new string[] {
            "Наименование as \'Наименование\'",
            "IDДолжности as \'I d должности\'",
            "Персонал.Контакты as \'Контакты\'"})]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fIDДолжности;
        
        private IIS.OtdelLogistiki.Персонал fПерсонал;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// IDДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должности.IDДолжности CustomAttributes)

        // *** End programmer edit section *** (Должности.IDДолжности CustomAttributes)
        public virtual int IDДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должности.IDДолжности Get start)

                // *** End programmer edit section *** (Должности.IDДолжности Get start)
                int result = this.fIDДолжности;
                // *** Start programmer edit section *** (Должности.IDДолжности Get end)

                // *** End programmer edit section *** (Должности.IDДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.IDДолжности Set start)

                // *** End programmer edit section *** (Должности.IDДолжности Set start)
                this.fIDДолжности = value;
                // *** Start programmer edit section *** (Должности.IDДолжности Set end)

                // *** End programmer edit section *** (Должности.IDДолжности Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Наименование CustomAttributes)

        // *** End programmer edit section *** (Должности.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Наименование Get start)

                // *** End programmer edit section *** (Должности.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Должности.Наименование Get end)

                // *** End programmer edit section *** (Должности.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Наименование Set start)

                // *** End programmer edit section *** (Должности.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Должности.Наименование Set end)

                // *** End programmer edit section *** (Должности.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Должности.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Персонал CustomAttributes)

        // *** End programmer edit section *** (Должности.Персонал CustomAttributes)
        [PropertyStorage(new string[] {
                "Персонал"})]
        [NotNull()]
        public virtual IIS.OtdelLogistiki.Персонал Персонал
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Персонал Get start)

                // *** End programmer edit section *** (Должности.Персонал Get start)
                IIS.OtdelLogistiki.Персонал result = this.fПерсонал;
                // *** Start programmer edit section *** (Должности.Персонал Get end)

                // *** End programmer edit section *** (Должности.Персонал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Персонал Set start)

                // *** End programmer edit section *** (Должности.Персонал Set start)
                this.fПерсонал = value;
                // *** Start programmer edit section *** (Должности.Персонал Set end)

                // *** End programmer edit section *** (Должности.Персонал Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиE", typeof(IIS.OtdelLogistiki.Должности));
                }
            }
            
            /// <summary>
            /// "ДолжностиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиL", typeof(IIS.OtdelLogistiki.Должности));
                }
            }
        }
    }
}
