//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtdelLogistiki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Путевой лист.
    /// </summary>
    // *** Start programmer edit section *** (ПутевойЛист CustomAttributes)

    // *** End programmer edit section *** (ПутевойЛист CustomAttributes)
    [AutoAltered()]
    [Caption("Путевой лист")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПутевойЛистE", new string[] {
            "ВыдатьТоплива as \'Выдать топлива\'",
            "Номер as \'Номер\'",
            "СопровожЛица as \'Сопровож лица\'",
            "ГаражНомер as \'Гараж номер\'",
            "РукОтдЛог as \'Рук отд лог\'",
            "РукОтдЛог.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "РукОтдЛог.ФИО"})]
    [MasterViewDefineAttribute("ПутевойЛистE", "РукОтдЛог", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ПутевойЛистL", new string[] {
            "ВыдатьТоплива as \'Выдать топлива\'",
            "Номер as \'Номер\'",
            "СопровожЛица as \'Сопровож лица\'",
            "ГаражНомер as \'Гараж номер\'",
            "РукОтдЛог.ФИО as \'ФИО\'"})]
    public class ПутевойЛист : ICSSoft.STORMNET.DataObject
    {
        
        private int fВыдатьТоплива;
        
        private int fНомер;
        
        private string fСопровожЛица;
        
        private int fГаражНомер;
        
        private IIS.OtdelLogistiki.РукОтдЛог fРукОтдЛог;
        
        // *** Start programmer edit section *** (ПутевойЛист CustomMembers)

        // *** End programmer edit section *** (ПутевойЛист CustomMembers)

        
        /// <summary>
        /// ВыдатьТоплива.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива CustomAttributes)
        public virtual int ВыдатьТоплива
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get start)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get start)
                int result = this.fВыдатьТоплива;
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get end)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set start)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set start)
                this.fВыдатьТоплива = value;
                // *** Start programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set end)

                // *** End programmer edit section *** (ПутевойЛист.ВыдатьТоплива Set end)
            }
        }
        
        /// <summary>
        /// ГаражНомер.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.ГаражНомер CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.ГаражНомер CustomAttributes)
        public virtual int ГаражНомер
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.ГаражНомер Get start)

                // *** End programmer edit section *** (ПутевойЛист.ГаражНомер Get start)
                int result = this.fГаражНомер;
                // *** Start programmer edit section *** (ПутевойЛист.ГаражНомер Get end)

                // *** End programmer edit section *** (ПутевойЛист.ГаражНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.ГаражНомер Set start)

                // *** End programmer edit section *** (ПутевойЛист.ГаражНомер Set start)
                this.fГаражНомер = value;
                // *** Start programmer edit section *** (ПутевойЛист.ГаражНомер Set end)

                // *** End programmer edit section *** (ПутевойЛист.ГаражНомер Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Номер CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Номер Get start)

                // *** End programmer edit section *** (ПутевойЛист.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПутевойЛист.Номер Get end)

                // *** End programmer edit section *** (ПутевойЛист.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Номер Set start)

                // *** End programmer edit section *** (ПутевойЛист.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПутевойЛист.Номер Set end)

                // *** End programmer edit section *** (ПутевойЛист.Номер Set end)
            }
        }
        
        /// <summary>
        /// СопровожЛица.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.СопровожЛица CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.СопровожЛица CustomAttributes)
        [StrLen(255)]
        public virtual string СопровожЛица
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.СопровожЛица Get start)

                // *** End programmer edit section *** (ПутевойЛист.СопровожЛица Get start)
                string result = this.fСопровожЛица;
                // *** Start programmer edit section *** (ПутевойЛист.СопровожЛица Get end)

                // *** End programmer edit section *** (ПутевойЛист.СопровожЛица Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.СопровожЛица Set start)

                // *** End programmer edit section *** (ПутевойЛист.СопровожЛица Set start)
                this.fСопровожЛица = value;
                // *** Start programmer edit section *** (ПутевойЛист.СопровожЛица Set end)

                // *** End programmer edit section *** (ПутевойЛист.СопровожЛица Set end)
            }
        }
        
        /// <summary>
        /// Путевой лист.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.РукОтдЛог CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.РукОтдЛог CustomAttributes)
        [PropertyStorage(new string[] {
                "РукОтдЛог"})]
        [NotNull()]
        public virtual IIS.OtdelLogistiki.РукОтдЛог РукОтдЛог
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.РукОтдЛог Get start)

                // *** End programmer edit section *** (ПутевойЛист.РукОтдЛог Get start)
                IIS.OtdelLogistiki.РукОтдЛог result = this.fРукОтдЛог;
                // *** Start programmer edit section *** (ПутевойЛист.РукОтдЛог Get end)

                // *** End programmer edit section *** (ПутевойЛист.РукОтдЛог Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.РукОтдЛог Set start)

                // *** End programmer edit section *** (ПутевойЛист.РукОтдЛог Set start)
                this.fРукОтдЛог = value;
                // *** Start programmer edit section *** (ПутевойЛист.РукОтдЛог Set end)

                // *** End programmer edit section *** (ПутевойЛист.РукОтдЛог Set end)
            }
        }
        
        // *** Start programmer edit section *** (ПутевойЛист.Распечатать CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Распечатать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Распечатать()
        {
            // *** Start programmer edit section *** (ПутевойЛист.Распечатать method implementation)
            return;
            // *** End programmer edit section *** (ПутевойЛист.Распечатать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПутевойЛистE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПутевойЛистE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПутевойЛистE", typeof(IIS.OtdelLogistiki.ПутевойЛист));
                }
            }
            
            /// <summary>
            /// "ПутевойЛистL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПутевойЛистL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПутевойЛистL", typeof(IIS.OtdelLogistiki.ПутевойЛист));
                }
            }
        }
    }
}
