//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtdelLogistiki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рук отд лог.
    /// </summary>
    // *** Start programmer edit section *** (РукОтдЛог CustomAttributes)

    // *** End programmer edit section *** (РукОтдЛог CustomAttributes)
    [AutoAltered()]
    [Caption("Рук отд лог")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РукОтдЛогE", new string[] {
            "ФИО as \'ФИО\'"})]
    [View("РукОтдЛогL", new string[] {
            "ФИО as \'ФИО\'"})]
    public class РукОтдЛог : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        // *** Start programmer edit section *** (РукОтдЛог CustomMembers)

        // *** End programmer edit section *** (РукОтдЛог CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (РукОтдЛог.ФИО CustomAttributes)

        // *** End programmer edit section *** (РукОтдЛог.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (РукОтдЛог.ФИО Get start)

                // *** End programmer edit section *** (РукОтдЛог.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (РукОтдЛог.ФИО Get end)

                // *** End programmer edit section *** (РукОтдЛог.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РукОтдЛог.ФИО Set start)

                // *** End programmer edit section *** (РукОтдЛог.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (РукОтдЛог.ФИО Set end)

                // *** End programmer edit section *** (РукОтдЛог.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РукОтдЛогE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РукОтдЛогE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РукОтдЛогE", typeof(IIS.OtdelLogistiki.РукОтдЛог));
                }
            }
            
            /// <summary>
            /// "РукОтдЛогL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РукОтдЛогL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РукОтдЛогL", typeof(IIS.OtdelLogistiki.РукОтдЛог));
                }
            }
        }
    }
}
