//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.OtdelLogistiki
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч движ ГСМ.
    /// </summary>
    // *** Start programmer edit section *** (ТчДвижГСМ CustomAttributes)

    // *** End programmer edit section *** (ТчДвижГСМ CustomAttributes)
    [AutoAltered()]
    [Caption("Тч движ ГСМ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчДвижГСМE", new string[] {
            "Количество as \'Количество\'",
            "Дата as \'Дата\'",
            "Остаток as \'Остаток\'",
            "МаркаГСМ as \'Марка ГСМ\'"})]
    [View("ТчДвижГСМL", new string[] {
            "Количество as \'Количество\'",
            "Дата as \'Дата\'",
            "Остаток as \'Остаток\'",
            "МаркаГСМ as \'Марка ГСМ\'"})]
    public class ТчДвижГСМ : ICSSoft.STORMNET.DataObject
    {
        
        private double fКоличество;
        
        private System.DateTime fДата;
        
        private double fОстаток;
        
        private string fМаркаГСМ;
        
        // *** Start programmer edit section *** (ТчДвижГСМ CustomMembers)

        // *** End programmer edit section *** (ТчДвижГСМ CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ТчДвижГСМ.Дата CustomAttributes)

        // *** End programmer edit section *** (ТчДвижГСМ.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Дата Get start)

                // *** End programmer edit section *** (ТчДвижГСМ.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ТчДвижГСМ.Дата Get end)

                // *** End programmer edit section *** (ТчДвижГСМ.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Дата Set start)

                // *** End programmer edit section *** (ТчДвижГСМ.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ТчДвижГСМ.Дата Set end)

                // *** End programmer edit section *** (ТчДвижГСМ.Дата Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТчДвижГСМ.Количество CustomAttributes)

        // *** End programmer edit section *** (ТчДвижГСМ.Количество CustomAttributes)
        public virtual double Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Количество Get start)

                // *** End programmer edit section *** (ТчДвижГСМ.Количество Get start)
                double result = this.fКоличество;
                // *** Start programmer edit section *** (ТчДвижГСМ.Количество Get end)

                // *** End programmer edit section *** (ТчДвижГСМ.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Количество Set start)

                // *** End programmer edit section *** (ТчДвижГСМ.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТчДвижГСМ.Количество Set end)

                // *** End programmer edit section *** (ТчДвижГСМ.Количество Set end)
            }
        }
        
        /// <summary>
        /// МаркаГСМ.
        /// </summary>
        // *** Start programmer edit section *** (ТчДвижГСМ.МаркаГСМ CustomAttributes)

        // *** End programmer edit section *** (ТчДвижГСМ.МаркаГСМ CustomAttributes)
        [StrLen(255)]
        public virtual string МаркаГСМ
        {
            get
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.МаркаГСМ Get start)

                // *** End programmer edit section *** (ТчДвижГСМ.МаркаГСМ Get start)
                string result = this.fМаркаГСМ;
                // *** Start programmer edit section *** (ТчДвижГСМ.МаркаГСМ Get end)

                // *** End programmer edit section *** (ТчДвижГСМ.МаркаГСМ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.МаркаГСМ Set start)

                // *** End programmer edit section *** (ТчДвижГСМ.МаркаГСМ Set start)
                this.fМаркаГСМ = value;
                // *** Start programmer edit section *** (ТчДвижГСМ.МаркаГСМ Set end)

                // *** End programmer edit section *** (ТчДвижГСМ.МаркаГСМ Set end)
            }
        }
        
        /// <summary>
        /// Остаток.
        /// </summary>
        // *** Start programmer edit section *** (ТчДвижГСМ.Остаток CustomAttributes)

        // *** End programmer edit section *** (ТчДвижГСМ.Остаток CustomAttributes)
        public virtual double Остаток
        {
            get
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Остаток Get start)

                // *** End programmer edit section *** (ТчДвижГСМ.Остаток Get start)
                double result = this.fОстаток;
                // *** Start programmer edit section *** (ТчДвижГСМ.Остаток Get end)

                // *** End programmer edit section *** (ТчДвижГСМ.Остаток Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчДвижГСМ.Остаток Set start)

                // *** End programmer edit section *** (ТчДвижГСМ.Остаток Set start)
                this.fОстаток = value;
                // *** Start programmer edit section *** (ТчДвижГСМ.Остаток Set end)

                // *** End programmer edit section *** (ТчДвижГСМ.Остаток Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчДвижГСМE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчДвижГСМE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчДвижГСМE", typeof(IIS.OtdelLogistiki.ТчДвижГСМ));
                }
            }
            
            /// <summary>
            /// "ТчДвижГСМL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчДвижГСМL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчДвижГСМL", typeof(IIS.OtdelLogistiki.ТчДвижГСМ));
                }
            }
        }
    }
}
